name: 'Build and Push Docker Image'
description: 'Builds a Docker image and pushes it to Docker Hub'
inputs:
  dockerfile-path:
    description: 'Path to the Dockerfile'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  image-tag:
    description: 'Docker image tag'
    required: true
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2

    - name: 'Log in to Docker Hub'
      shell: bash
      run: echo "${{ inputs.password }}" | docker login -u "${{ inputs.username }}" --password-stdin

    - name: 'Build Docker image'
      shell: bash
      run: docker build -t ${{ inputs.image-name }}:${{ inputs.image-tag }} -f ${{ inputs.dockerfile-path }} .

    - name: 'Push Docker image'
      shell: bash
      run: docker push ${{ inputs.image-name }}:${{ inputs.image-tag }}
