trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name rg-tfstate --location westeurope
      az storage account create --name stg9834tfstate --resource-group rg-tfstate --location westeurope --sku Standard_LRS
      az storage container create --name tfstate --account-name stg9834tfstate